### ISSUE TITLE
Bash not found

### ISSUE THREAD

**Issue by fntlnz** [gianarb/slimmer#1]
I'd allow the user to pass the script to be executed here https://github.com/gianarb/slimmer/blob/master/command/build.go#L50

For example in most of my containers I don't have bash at all 

```
2016/02/23 Build 9e39096b9056 started - source my/php-fpm:7.0.3

1
exec: "bash": executable file not found in $PATH
```

**Comment by gianarb** [comment]
I can read this information from the header of the script.. for example something like 

``` php
#!/bin/bash
```

do it seem ok? :)

**Comment by fntlnz** [comment]
A good option could be removing `bash` in favor of a generic `build.slimmer` that have to be executable
and has a shebang line with the desired executor

**Comment by gianarb** [comment]
Nop the problem is that it is not an exec file.. grrrr

**Comment by gianarb** [comment]
Yes I will your suggestion! :+1:
