### ISSUE TITLE
Don't use the /tmp directory as default

### ISSUE THREAD

**Issue by fntlnz** [gianarb/slimmer#2]
I'd not use the `/tmp` directory by default. A better alternative could be something like /slimmer

https://github.com/gianarb/slimmer/blob/master/command/build.go#L37

**Comment by gianarb** [comment]
Ok,
On this topic I am thinking to replace che VOLUME with a COPY..
Feedback about this approach?

**Comment by fntlnz** [comment]
better a readonly volume, you are just running right? Not building a dockerfile

Just like:

```
docker run -v /my:/slimmer:ro etc..
```

**Comment by gianarb** [comment]
`:ro` is a magic!!!
